### ISSUE TITLE
A list of supported ID commands

### ISSUE THREAD

**Issue by dizcza** [Sensirion/python-shdlc-driver#2]
There is a comment in your usage example
```python
    # Execute custom command
    raw_response = device.execute(ShdlcCommand(
        id=0xD2,  # The command ID as specified in the device documentation
        data=b"\x01",  # The payload data to send
        max_response_time=0.2,  # Maximum response time in Seconds
    ))
```
Could you please link the device documentation with a list of supported ID commands? In particular, what's the command to initialize and read a differential pressure from an SDP31 device using your API?
Thank you.

**Comment by ubruhin** [comment]
Hi @dizcza,

This driver is for SHDLC (UART) sensors, but SDP31 has an I2C interface. So you need to use [`sensirion-i2c-driver`](https://sensirion.github.io/python-i2c-driver/) instead. See there how to send I2C commands. If you have connected the SDP31 sensor using a SensorBridge, see also the [SensorBridge documentation](https://sensirion.github.io/python-shdlc-sensorbridge/index.html).

The available command IDs depend on the connected sensor and thus are documented in the sensors datasheet.

Closing this issue since it is not related to the SHDLC driver.
